import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Scissors, Layers, Sparkles, Heart, Flame, 
  Menu, X, Laptop, ArrowRight 
} from "lucide-react";

import HomeView from "./components/HomeView";
import FabricsView from "./components/FabricsView";
import PatternsView from "./components/PatternsView";
import ShowcaseView from "./components/ShowcaseView";
import StudioView from "./components/StudioView";

import { DEFAULT_FABRICS, COMMUNITY_SHOWCASE } from "./data";
import { Fabric, ActiveScreen } from "./types";

export default function App() {
  const [activeScreen, setActiveScreen] = useState<ActiveScreen>("home");
  const [fabrics, setFabrics] = useState<Fabric[]>(DEFAULT_FABRICS);
  const [activeStudioFabricIds, setActiveStudioFabricIds] = useState<string[]>([
    "emerald-silk",
    "raw-selvedge",
    "ruby-velvet",
    "chantilly-lace"
  ]);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  // Add custom fabric generated by AI
  const handleAddFabric = (newFabric: Fabric) => {
    setFabrics(prev => [newFabric, ...prev]);
    // Auto-load custom AI fabrics into Active Studio list for instant use
    if (!activeStudioFabricIds.includes(newFabric.id)) {
      setActiveStudioFabricIds(prev => [newFabric.id, ...prev]);
    }
  };

  // Toggle fabric inclusion in the Studio Workspace
  const handleSelectFabricForStudio = (fabric: Fabric) => {
    if (activeStudioFabricIds.includes(fabric.id)) {
      setActiveStudioFabricIds(prev => prev.filter(id => id !== fabric.id));
    } else {
      setActiveStudioFabricIds(prev => [...prev, fabric.id]);
    }
  };

  // Navigate helper
  const handleNavigate = (screen: ActiveScreen) => {
    setActiveScreen(screen);
    setMobileMenuOpen(false);
  };

  return (
    <div className="min-h-screen bg-background font-sans text-on-surface select-none relative pb-12">
      {/* Decorative Outer Border Lines representing bespoke pattern layout marks */}
      <div className="absolute top-0 bottom-0 left-4 w-[1px] bg-on-surface/5 pointer-events-none hidden md:block"></div>
      <div className="absolute top-0 bottom-0 right-4 w-[1px] bg-on-surface/5 pointer-events-none hidden md:block"></div>

      {/* Primary Header Navbar */}
      <header className="sticky top-0 bg-surface/85 backdrop-blur-md border-b-2 border-on-surface z-40 px-4 md:px-8 py-4">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          {/* Logo Brand Title */}
          <div 
            id="brand-logo"
            onClick={() => handleNavigate("home")} 
            className="flex items-center gap-2 cursor-pointer"
          >
            <div className="bg-primary text-on-primary p-1.5 rounded border border-on-surface font-black shadow-sm sticker-border flex items-center justify-center">
              <Scissors className="w-4 h-4" />
            </div>
            <span className="font-display font-extrabold tracking-tight text-xl md:text-2xl uppercase">
              Style<span className="text-primary font-black">Forge</span>
            </span>
          </div>

          {/* Desktop Navigation Links */}
          <nav className="hidden md:flex items-center gap-1.5 bg-surface-container-low border border-on-surface/10 p-1.5 rounded-lg">
            <button
              id="nav-studio"
              onClick={() => handleNavigate("studio")}
              className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-md transition-all cursor-pointer flex items-center gap-1.5 ${
                activeScreen === "studio"
                  ? "bg-on-surface text-surface font-extrabold"
                  : "text-on-surface-variant hover:text-on-surface hover:bg-surface-container"
              }`}
            >
              <Scissors className="w-3.5 h-3.5" /> Studio
            </button>

            <button
              id="nav-fabrics"
              onClick={() => handleNavigate("fabrics")}
              className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-md transition-all cursor-pointer flex items-center gap-1.5 ${
                activeScreen === "fabrics"
                  ? "bg-on-surface text-surface font-extrabold"
                  : "text-on-surface-variant hover:text-on-surface hover:bg-surface-container"
              }`}
            >
              <Layers className="w-3.5 h-3.5" /> Textile Wall
            </button>

            <button
              id="nav-patterns"
              onClick={() => handleNavigate("patterns")}
              className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-md transition-all cursor-pointer flex items-center gap-1.5 ${
                activeScreen === "patterns"
                  ? "bg-on-surface text-surface font-extrabold"
                  : "text-on-surface-variant hover:text-on-surface hover:bg-surface-container"
              }`}
            >
              <Sparkles className="w-3.5 h-3.5" /> Infinite Patterns
            </button>

            <button
              id="nav-showcase"
              onClick={() => handleNavigate("showcase")}
              className={`px-4 py-2 text-xs font-bold uppercase tracking-wider rounded-md transition-all cursor-pointer flex items-center gap-1.5 ${
                activeScreen === "showcase"
                  ? "bg-on-surface text-surface font-extrabold"
                  : "text-on-surface-variant hover:text-on-surface hover:bg-surface-container"
              }`}
            >
              <Heart className="w-3.5 h-3.5" /> Showcase
            </button>
          </nav>

          {/* Right Header Controls */}
          <div className="flex items-center gap-3">
            {activeScreen !== "home" && (
              <button 
                id="header-cta-home"
                onClick={() => handleNavigate("home")}
                className="hidden md:flex px-4 py-2 bg-primary-fixed text-on-primary-fixed border border-on-surface/20 rounded-lg text-xs font-bold uppercase tracking-wider items-center gap-1.5 hover:bg-primary-fixed-dim cursor-pointer"
              >
                Launchpad
              </button>
            )}

            {/* Mobile Menu Icon */}
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="md:hidden w-10 h-10 border-2 border-on-surface rounded-lg flex items-center justify-center bg-surface hover:bg-surface-container active:scale-95 cursor-pointer"
            >
              {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </div>
        </div>
      </header>

      {/* Mobile Drawer Navigation overlay */}
      <AnimatePresence>
        {mobileMenuOpen && (
          <motion.div
            className="fixed inset-0 bg-on-surface/60 backdrop-blur-sm z-30 md:hidden flex justify-end"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setMobileMenuOpen(false)}
          >
            <motion.div
              className="bg-surface w-4/5 max-w-sm h-full border-l-2 border-on-surface p-6 flex flex-col justify-between"
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ type: "spring", damping: 25, stiffness: 200 }}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="space-y-6">
                <span className="font-display font-extrabold uppercase tracking-tight text-xl text-on-surface">
                  Navigation
                </span>

                <div className="space-y-3 pt-4 border-t border-on-surface/10">
                  <button
                    onClick={() => handleNavigate("home")}
                    className="w-full text-left py-3 font-bold uppercase text-sm tracking-wider border-b border-on-surface/5 flex items-center justify-between"
                  >
                    <span>Launchpad</span>
                    <ArrowRight className="w-4 h-4 text-primary" />
                  </button>

                  <button
                    onClick={() => handleNavigate("studio")}
                    className="w-full text-left py-3 font-bold uppercase text-sm tracking-wider border-b border-on-surface/5 flex items-center justify-between"
                  >
                    <span>Couture Workshop</span>
                    <Scissors className="w-4 h-4 text-primary" />
                  </button>

                  <button
                    onClick={() => handleNavigate("fabrics")}
                    className="w-full text-left py-3 font-bold uppercase text-sm tracking-wider border-b border-on-surface/5 flex items-center justify-between"
                  >
                    <span>Material Texture Wall</span>
                    <Layers className="w-4 h-4 text-secondary" />
                  </button>

                  <button
                    onClick={() => handleNavigate("patterns")}
                    className="w-full text-left py-3 font-bold uppercase text-sm tracking-wider border-b border-on-surface/5 flex items-center justify-between"
                  >
                    <span>Infinite Patterns</span>
                    <Sparkles className="w-4 h-4 text-tertiary" />
                  </button>

                  <button
                    onClick={() => handleNavigate("showcase")}
                    className="w-full text-left py-3 font-bold uppercase text-sm tracking-wider border-b border-on-surface/5 flex items-center justify-between"
                  >
                    <span>Community Showcase</span>
                    <Heart className="w-4 h-4 text-red-500" />
                  </button>
                </div>
              </div>

              <div className="bg-surface-container-low border border-on-surface/10 p-4 rounded-xl text-center">
                <span className="text-[10px] font-black uppercase tracking-wider text-on-surface-variant block mb-1">
                  StyleForge Edition 2026
                </span>
                <p className="text-[9px] font-medium leading-relaxed text-on-surface-variant/70">
                  Crafted meticulously for modern digital creators.
                </p>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Screen Router Outlet */}
      <main className="relative z-10 pt-4">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeScreen}
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            transition={{ duration: 0.35, ease: "easeInOut" }}
          >
            {activeScreen === "home" && (
              <HomeView onNavigate={handleNavigate} />
            )}

            {activeScreen === "fabrics" && (
              <FabricsView 
                fabrics={fabrics} 
                onAddFabric={handleAddFabric} 
                onSelectFabricForStudio={handleSelectFabricForStudio}
                activeStudioFabricIds={activeStudioFabricIds}
              />
            )}

            {activeScreen === "patterns" && (
              <PatternsView />
            )}

            {activeScreen === "showcase" && (
              <ShowcaseView 
                designs={COMMUNITY_SHOWCASE} 
                fabrics={fabrics}
                onSelectFabricForStudio={handleSelectFabricForStudio}
                activeStudioFabricIds={activeStudioFabricIds}
              />
            )}

            {activeScreen === "studio" && (
              <StudioView 
                fabrics={fabrics}
                activeStudioFabricIds={activeStudioFabricIds}
                onSelectFabricForStudio={handleSelectFabricForStudio}
              />
            )}
          </motion.div>
        </AnimatePresence>
      </main>

      {/* Global Bottom Tape Measure Line Footer Decoration */}
      <footer className="absolute bottom-0 left-0 w-full opacity-10">
        <div className="measuring-tape"></div>
      </footer>
    </div>
  );
}
